#!/bin/bash
# Build hook for Docker hub auto-build
# https://docs.docker.com/docker-hub/builds/advanced/#custom-build-phase-hooks

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"

export $(grep -v '^#' ../template.env | xargs)

docker pull $DOCKER_REPO:core-latest

docker build \
    --build-arg MISP_TAG=$MISP_TAG \
    --build-arg PHP_VER=$PHP_VER \
    --build-arg BUILD_RFC3339=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
    --build-arg COMMIT=$(git rev-parse --short HEAD) \
    --build-arg VERSION=$(git describe --tags --always) \
    -t $IMAGE_NAME .
