version: '3'

services:
  misp:
    image: marcelosz/misp:core-latest
    build:
        context: core/.
        args:
            - PHP_VER=${PHP_VER}
            - MISP_TAG=${MISP_TAG}
  misp-modules:
    image: marcelosz/misp:modules-latest
    build:
        context: modules/.
        args:
            - MODULES_TAG=${MODULES_TAG}
